### ISSUE TITLE
FABRIC-install chaincode job fails due incorrect chaincode path

### ISSUE THREAD

**Issue by bafsunsu** [hyperledger-labs/blockchain-automation-framework#1166] opened 2020-11-10 08:57 UTC
**Describe the bug**

Chaincode installation jobs fails for fabric 2.0.0 with error as 
"Error: error getting chaincode deployment spec for CHAINCODE_NAME"
For "platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml" at line number 154 we perform a change directory with "cd $GOPATH/src/github.com/chaincode && dep ensure"  command but then again on line no 156 for peer chaincode install command we are using the chaincode path variable value as. "-p github.com/chaincode/${CHAINCODE_NAME}/${CHAINCODE_MAINDIR}" which is not reachable from the present directory which is already at $GOPATH/src/github.com/chaincode/ and the install command is not able to find the chaincode to install

Branch:Master

**To Reproduce**
1. Set up a new fabric network with details of chaincode to be installed
2.  At chaincode installation step look for logs of Job "installchaincode-{{ $.Values.peer.name }}-{{ $.Values.chaincode.name }}-{{ $.Values.chaincode.version }}"
3. the job would fail with "Error: error getting chaincode deployment spec for <chaincode_name>: exit status 1
4. Re executing same commands of install_chaincode.yaml file through a peer cli would present the same error

**Expected behavior**
Chaincode to get installed and instantiated on the network

**Screenshots**

**Environment (please complete the following information):**
 - Azure Kubernetes service
 - Version 2.0.0

**Additional context**

**Comment by lakshyakumar** [comment] 2020-11-23 11:21
hi @bafsunsu , can you please provide us more details on the issue as we are not able to reproduce the same from the master branch.
Also a seperate point being we are not actively supporting Hyperledger-Fabric v2.0.0, currently we are supporting HL Fabric v1.4.4 and v2.2.x is in active development.

**Comment by bafsunsu** [comment] 2020-11-29 14:30
@lakshyakumar Sorry there was little mistake in the issue description as I had mentioned instantiate_chaincode.yaml files reference instead of install_chaincode.yaml file at "platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml"

Have updated the issue description and also have created a pull request for this issue fix from my public git hub id(accidentally created issue through baf test github ID)

**Comment by suvajit-sarkar** [comment] 2021-01-04 13:14
Can you verify is this is a valid bug on Fabric 2.2 latest code

**Comment by suvajit-sarkar** [comment] 2021-02-01 12:57
Closing this issue as Fabric version 2.0.0 is not actively supported by BAF anymore and the bug is not reproducible in the supported fabric version (2.2 and 1.4.4)

**Closed by suvajit-sarkar** 2021-02-01 12:57 UTC
Labels: bug, fabric
