### ISSUE TITLE
Create a new peer under existing org

### ISSUE THREAD

**Issue by himanshulalarya** [hyperledger-labs/blockchain-automation-framework#1029] opened 2020-09-14 09:48 UTC
### Description
Create a new peer under existing org and join the existing channel in a running Fabric network.

### Acceptance Criteria
1. Add new peer to existing org
2. Join the peer to existing channel

**Comment by suvajit-sarkar** [comment] 2020-10-12 08:36
closing this issue as it is a duplicate of #1022

**Closed by suvajit-sarkar** 2020-10-12 08:36 UTC
