### ISSUE TITLE
BAF with fabric 2.2.0: secrets for user1 not saved fully 

### ISSUE THREAD

**Issue by kawthers** [hyperledger-labs/blockchain-automation-framework#1306] opened 2021-02-16 21:09 UTC
After network deployed successfully.

Vault screenshot:
![user1msp](https://user-images.githubusercontent.com/63705718/108121405-7041a180-70ab-11eb-9832-2e6c1089b9f1.png)

For every organizations, user1/msp consist only private key

**Expected behavior**
All secrets must be there upon user enroll.

for Admin user all secrets saved fine.

**Comment by alvaropicazo** [comment] 2021-02-17 09:51
Just checked! The issue exists.

**Comment by maximusGit** [comment] 2021-02-23 12:40
Hi team) Any idea, when this will be fixed?

**Comment by HolliMUC** [comment] 2021-03-01 09:01
Hi! I am having same issue, when this will be fixed?  - unfortunatly we cannot continue to deploy until this bug is fixed.....we are hooked on it.........Thanks in advance.

**Comment by alvaropicazo** [comment] 2021-03-01 12:29
Hi @maximusGit @HolliMUC , today this issue will be discussed in our sprint planning and will be given some priority to this, I will keep you updated.

**Comment by alvaropicazo** [comment] 2021-03-10 16:06
The problem is checked. So in the ca-server, there is a error log like this: 

[DEBUG] CA Files: [/crypto-config/peerOrganizations/malv-net/ca/ca.malv-net-cert.pem]\n2021/03/10 13:05:36 [DEBUG] Client Cert File: \n2021/03/10 13:05:36 [DEBUG] Client Key File: \n2021/03/10 13:05:36 [DEBUG] Client TLS certificate and/or key file not provided\n2021/03/10 13:05:36 [DEBUG] Loading identity: keyFile=/root/ca-tools/cas/ca-malv/msp/keystore/key.pem, certFile=/root/ca-tools/cas/ca-malv/msp/signcerts/cert.pem\n2021/03/10 13:05:36 [DEBUG] **No credential found at /root/ca-tools/cas/ca-malv/msp/user/SignerConfig**: open /root/ca-tools/cas/ca-malv/msp/user/SignerConfig: no such file or directory\n2021/03/10 13:05:36 [DEBUG] No Idemix credential found at /root/ca-tools/cas/ca-malv/msp/user/SignerConfig\n2021/03/10 13:05:36 [DEBUG] Register { Name:User1@malv-net Type:user Secret:**** MaxEnrollments:0 Affiliation:malv Attributes:[{hf.Revoker true false}] CAName:  }\n2021/03/10 13:05:36 [DEBUG] Adding token-based authorization header\n2021/03/10 13:05:36 [DEBUG] Sending request\nPOST https://ca.malv-net:7054/register\n{\"id\":\"User1@malv-net\",\"type\":\"user\",\"secret\":\"User1@malv-net-pw\",\"affiliation\":\"malv\",\"attrs\":[{\"name\":\"hf.Revoker\",\"value\":\"true\"}]}\n2021/03/10 13:05:36 [DEBUG] Received response\nstatusCode=500 (500 Internal Server Error)\nError: **Response from server: Error Code: 0 - R**egistration of 'User1@malv-net' failed in affiliation validation: Failed getting affiliation 'malv': : scode: 404, code: 63, msg: Failed to get Affiliation: sql: no rows in result set**\n\n+** fabric-ca-client enroll -d -u https://User1@malv-net:User1@malv-net-pw@ca.malv-net:7054 --csr.names

**Comment by jagpreetsinghsasan** [comment] 2021-03-12 09:23
@all-contributors please add @RafaelAPB  for contributing

**Comment by jagpreetsinghsasan** [comment] 2021-03-12 09:24
@all-contributors please add @RafaelAPB  for maintainance

**Comment by jagpreetsinghsasan** [comment] 2021-03-12 09:25
@all-contributors please add @RafaelAPB for maintenance

**Comment by jagpreetsinghsasan** [comment] 2021-03-12 09:35
@all-contributors please add @alvaropicazo for maintenance

**Closed** 2021-03-22 10:34 UTC
Labels: bug, fabric
